### PR TITLE
Docs: Grammar edits / rephrases.

### PR DESCRIPTION
**Pull request by bjones1**
I went through the site and tried to edit / tweak / rephrase.

Still to do: a CodeChat screenshot...

### CODE REVIEW

**Comment by hlamer** [comment]
Thank you very much! Monkey Studio/Enki project was missing a native speaker since the beginning.

I replaced `Contributor to literate programming functionality.` with `Creator of ..`

What is good way to say 'Tested on Linux and Windows. It is reported it works on MacOSX`?

I can make a screenshot, so, all screenshots will have the same GUI theme and size. But I need a idea what to shot from you.

**Comment by bjones1** [comment]
Sounds good. For a proposal I wrote, I created some annotated screen shots. This isn't just a pure screen shot; do you think something like this would fit?

Perhaps a bit less annotation, but I was thinking of two screen shots:

1. Something which points out that the preview and editor windows are synchronzied.
2. Something which shows literate programming (images, equations, hyperlinks, titles, etc.) in action.
codechat screenshot 4 - integrating equations and diagrams
codechat screenshot 1 - split-screen view with python interpreter

**Comment by bjones1** [comment]
Re: literate programming creator -- thanks, sounds good.

Re: a rewording for "Tested on Linux and Windows. It is reported it works on MacOSX." How about  "Tested on Linux and Windows. Users report that Enki works Mac OS X."

**Comment by hlamer** [comment]
First screenshot: I think it will be clear, if we just show code window and preview. Without annotation. Probably with specially fabricated contents. (See next paragraph)

Second screenshot: Don't need to show the interpreter. There are separate screenshot for it. I think we can avoid annotation if create special document which describes preview functionality. Like 

```
Underlines become titles
===================

[Links](http://enki-editor.org) are supported ...
```
What do you think about it?

I added some info at the end of "Markdown, HTML, reStructuredText live preview". But, now it is not enough visible.

Thank you. I fixed the line about Mac support.

**Comment by bjones1** [comment]
That sounds good to me. I'll be happy to contribute something, or edit whatever you come up with.

**Comment by hlamer** [comment]
I could try to do better Preview screenshot. But I think you would make better literate programming illustration.

**Comment by bjones1** [comment]
OK, I'll work on a file. Where would you like to keep it (which branch and subdirectory)?

**Comment by hlamer** [comment]
Create a directory, which starts on `_` in the `gh-pages` root. So it will not be visible on the site

**Comment by bjones1** [comment]
I just submitted https://github.com/hlamer/enki/pull/284. Comments / feedback welcome!

**Pull request merged**
