### PR TITLE
Back up session when files are specified in command line

### PR DESCRIPTION
**Pull request by vi**
Note: this also include a commit from "ENKI_SESSION" branch.

### CODE REVIEW

**Comment by hlamer** [comment]
How to restore a backuped  session? Manually move the file in `.config/enki?`

**Comment by vi** [comment]
Yes, the file name is mentioned in stderr output in some cases. And filename like `qqq.ext.bak` impiles there is also `qqq.ext`.

**Comment by hlamer** [comment]
Hmm. I don't like the idea of manually copying files. Enki is going to be more intuitive than old school editors. Regular user even don't have to know, where the files are stored.
How about
* If file is passed in the command line and ENKI_SESSION is set  - do not save the session. But
* If file is passed in the command line and --session is set  save the session

Don't need to do any backups.

**Comment by hlamer** [comment]
> I'm not sure where in user manual there should be info about sessions. There is no "Starting Enki" section.

Create a section `Session management`

**Comment by vi** [comment]
My primary reason for session backup is to avoid "why I see this sole little config file auto-opened opened instead of my 20 project files as before? Does I mean I need to remember which files I need to work on again?" in the default session. With named session support the feature is indeed less important.

**Comment by hlamer** [comment]
Can you use a named session for 20 project files or for little config to avoid overwriting the session?
I.e.
`enki -s bigproject` and `enki /etc/network/interfaces` or 

`enki` and `enki  -s tmp /etc/network/interfaces`

**Comment by vi** [comment]
Yes, if I think in advance about naming a session.

I just have lost an Enki sesion a couple of times, and every time thinked about the session backups (before I though about named sessions).

The timeline was:

1. Losing Enki sessions a couple of times, thinking about "there need to be session backups";
2. Looking into `~/.config/enki/`, finding `session.json` here;
3. Thinking "Hey, if we make it overridable from envvar, there may be multi-session";
4. Thinking "This change looks very easy, let's just do it - it's open source after all";
5. `git grep session` -> implement ENKI_SESSION -> commit;
6. Seems to be a feature useful for others as well => pull request;
7. I remember about backups (point "1.") and have a code for dealing with Enki sessions already opened. Implemented until I closed&forgot it.
8. "Pull requests for the pull request god".

Maybe now (after implementing "named session") the backups are less important, as "default session" should not be used for long-term set of open files, only for quick editing for a script or config.

**Comment by hlamer** [comment]
I understand the losing session problem, but still don't like the idea of manually copying files.
So, I'll not merge it now. Some other solution might be invented in the future.
Since Enki is OSS, you can always have your session backup commit on the top of the upstream tree.

Thank you for the manual edit!

**Pull request closed without merging**
