### PR TITLE
Mathjax fix

### PR DESCRIPTION
**Pull request by bjones1**
This places a better Markdown MathJax extension in the preview plugin and uses it instead.

### CODE REVIEW

**Comment by hlamer** [comment]
Hmm. I'm not sure it is a good idea to include to the sources a package which is available from pip, but ok, let's do it.
It seems like this pull request should be for v15.11 but not for master. Will merge manually tomorrow

**Comment by hlamer** [comment]
This extension works fine with markdown 2.6 from pip, but not with markdown 2.4 from Ubuntu 14.04 repo. Bryan, maybe you can check this? I think the fix will be simple. Seems like something has changed about extension configuration.

**Comment by bjones1** [comment]
I'll take a look!

**Comment by hlamer** [comment]
Cool. Merged it to v15.11

**Pull request closed without merging**
