### PR TITLE
Split gui

### PR DESCRIPTION
**Pull request by bjones1**
Address issue https://github.com/bjones1/enki/issues/38 by splitting the Preview settings GUI into two separate panels.

### CODE REVIEW

**Comment by hlamer** [comment]
Thanks!

`Documentation generat...` does not fit in the list view. Do you mind renaming it to `Shpinx documentation`?

**Comment by bjones1** [comment]
Eventually, I'd like to add support for other documentation generators (doxygen, javadoc, etc.), hence the title. Ideas:

1. Break it into two lines? "Documentation\n generators"?
2. Shorten it to "Doc. generators"
3. Just use "Sphinx"

**Comment by hlamer** [comment]
It won't be difficult to change the name later when we support one more doc generator. So, "Sphinx"
Btw,  during day time under Europe I'm often available on irc.freenode.net #enki for quicker interaction

**Comment by bjones1** [comment]
Sphinx sounds good. I'll submit a pull request.

I'll try IRC when it's daytime for you...

**Comment by hlamer** [comment]
I'll just rename. Too many burocracy for 1 word

-----Исходное сообщение-----
От: "bjones1" <notifications@github.com>
Отправлено: ‎30.‎04.‎2015 18:38
Кому: "hlamer/enki" <enki@noreply.github.com>
Копия: "Andrei Kopats" <hlamer@tut.by>
Тема: Re: [enki] Split gui (#281)

Sphinx sounds good. I'll submit a pull request.
I'll try IRC when it's daytime for you...

**Comment by bjones1** [comment]
OK, thanks!

**Pull request merged**
