### PR TITLE
Add: Quick way to set the Sphinx path based on the current project directory

### PR DESCRIPTION
**Pull request by bjones1**
I put this in the tools menu -- does this seem reasonable?

### CODE REVIEW

**Comment by hlamer** [comment]
Hmm. I generally dislike our way of setting sphinx project path in the global application settings. (However don't have an idea how to do it better.)

The majority of uses doesn't use Sphinx. So, lets show this action only when sphinx project is enabled.

**Comment by hlamer** [comment]
Just an idea. Now we have a project. Can we try to find `conf.py` among project files automatically?

**Comment by bjones1** [comment]
That makes sense -- I'll enable this only if Sphinx is enabled. I'm not sure what to do when `conf.py` is found. Note that the directory where `conf.py` lives doesn't have to be the same as the Sphinx source directory per http://sphinx-doc.org/glossary.html#term-configuration-directory.

**Comment by hlamer** [comment]
Move the action initialization from `_createDock()` to the plugin constructor. Now I can't set the path until some preview-able file is opened.

**Comment by bjones1** [comment]
Good point. Will do!

**Comment by bjones1** [comment]
Thanks for finding this bug! Fixed.

**Comment by hlamer** [comment]
Merged to `master` with additional fix.
Bryan, could you document Sphinx functionality (including this action) in the user manual?
Now there are a small page and a broken link to CodeChat tutorial

**Comment by bjones1** [comment]
Thanks! I'll add some docs and a fixed link.

**Comment by bjones1** [comment]
Docs added. Does this cover it?

**Comment by hlamer** [comment]
Yes, now it better!

2 more optional suggestions:
* Add a screenshots to Sphinx and Literate programming pages. One picture sometimes tells more than a page of text
* Add to Sphinx settings page a description similar to one located on CodeChat page.

**Comment by bjones1** [comment]
Good ideas. Done!

**Comment by hlamer** [comment]
Thanks!
I replaced Sphinx screenshot with Enki documentation index page. It contains table of contents, navigation bar. So, it is more clear what is difference of .rst preview and true Sphinx. I hope you don't mind?

**Comment by bjones1** [comment]
Looks good to me!

**Pull request closed without merging**
