### PR TITLE
Add: A short CodeChat demo Sphinx project.

### PR DESCRIPTION
**Pull request by bjones1**
I'm using Sphinx 1.3.1 to generate the output. If you have Sphinx 1.2, change html_theme = 'default' in conf.py.

### CODE REVIEW

**Comment by hlamer** [comment]
Got next backtrace when trying to build the project

```
Running Sphinx v1.3.1
loading pickled environment... not yet created

Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/sphinx/config.py", line 368, in __getattr__
    raise AttributeError('No such config value: %s' % name)
AttributeError: No such config value: exclude_trees
The full traceback has been saved in /tmp/sphinx-err-4trUt4.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

I'll try to fix it later. Don't have time now.

Thank you for the wiki fixes!

**Comment by bjones1** [comment]
Oops. You need an updated version of CodeChat for Sphinx 1.3. I haven't released it yet (still a few tweaks remain). Would you mind pulling from my bitbucket repo and using that version?
```
hg clone https://bitbucket.org/bjones/documentation
cd documentation
sudo python setup.py install
```

**Comment by bjones1** [comment]
My pleasure re: wiki fixes. I'll make a pass through the GUI next.

**Comment by hlamer** [comment]
Enki window is quite small on the screenshots on the main page. The text doesn't fit to it. I tried to make a smaller page. Look at http://enki-editor.org/screenshots/codechat.png.
[The source](https://github.com/hlamer/enki/blob/gh-pages/_codechat_demo/codechat_demo_short.py)

It is not published yet because I don't have code highlighting.  Do you have an idea why?
```
a@a-desktop ~/code/enki.gh-pages/_codechat_demo (gh-pages)$ pip freeze  | egrep  '(CodeChat|Sphinx|Pigments)'
CodeChat==0.0.19a1
Pigments==1.6
Sphinx==1.3.1
```

I like the big file (screenshot). I think we should use it for a blog post about literate programming.

**Comment by bjones1** [comment]
Oops, should be fixed by https://github.com/hlamer/enki/pull/290.

A blog post sounds great! I'm working on a tutorial, but can put that next on the list if you like help in authoring it.

**Comment by hlamer** [comment]
Maybe you could write the post? You are the author of the functionality, so nobody understands better than you why it is so cool.
I don't think we need a huge post. Just something like [this](http://enki-editor.org/2015/05/01/Vim_mode.html).

**Comment by hlamer** [comment]
Updated `gh-pages`, `hg pull -u` says "No changes". Still don't have code highlighting :-/

**Comment by bjones1** [comment]
Hmmm. Not sure what's wrong. Here's a Mint 16 screenshot from me. One possibility: the name for the syntax highlighter is P**y**gments:

```
bjones@bjones-VirtualBox ~/enki_all/enki_web $ pip freeze  | egrep  '(CodeChat|Sphinx|Pygments)'
CodeChat==0.0.19a1
Pygments==2.0.2
Sphinx==1.3.1
```

image

**Comment by hlamer** [comment]
Pygments also is installed.

Maybe you can:
* Go to Appearance settings and set it like on the screenshots
* Checkout `screenshos` Enki branch
* Run Enki from it and **do not** resize the window
* Switch off Pylint in the settings, set font size 9
* Open `codechat_demo_short.py`
* Move the mouse pointer from the window
* Make the screenshot

I hope it will look just like my screenshot, but with code highlighting

codechat
screenshot-customize theme
screenshot-customize theme-1

**Comment by bjones1** [comment]
Still catching up a bit, but will do soon...

**Comment by bjones1** [comment]
Andrei,

I'm trying to do this, but struck. I'm running Mine 16, but don't see how
to set the window border. All I can find is to apply the Mint-X theme, but
I can't find a place in settings to customize it. What am I missing?

[image: Inline image 1]

Bryan

On Tue, May 19, 2015 at 2:01 PM, Andrei Kopats <notifications@github.com>
wrote:

>  Pygments also is installed.
>
> Maybe you can:
>
>    - Go to Appearance settings and set it like on the screenshots
>    - Checkout screenshos Enki branch
>    - Run Enki from it and *do not* resize the window
>    - Switch off Pylint in the settings, set font size 9
>    - Open codechat_demo_short.py
>    - Move the mouse pointer from the window
>    - Make the screenshot
>
> I hope it will look just like my screenshot, but with code highlighting
>
> [image: codechat]
> <https://cloud.githubusercontent.com/assets/419720/7711233/cf2e971e-fe71-11e4-8de0-ba9f0380537c.png>
> [image: screenshot-customize theme]
> <https://cloud.githubusercontent.com/assets/419720/7711234/cf326fe2-fe71-11e4-8258-d26b9c31b35f.png>
> [image: screenshot-customize theme-1]
> <https://cloud.githubusercontent.com/assets/419720/7711235/cf342b98-fe71-11e4-84b6-569c6ab06d8c.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hlamer/enki/pull/284#issuecomment-103634455>.
>



-- 
Bryan A. Jones, Ph.D.
Associate Professor
Department of Electrical and Computer Engineering
231 Simrall / PO Box 9571
Mississippi State University
Mississippi state, MS 39762
http://www.ece.msstate.edu/~bjones
bjones AT ece DOT msstate DOT edu
voice 662-325-3149
fax 662-325-2298

Our Master, Jesus Christ, is on his way. He'll show up right on
time, his arrival guaranteed by the Blessed and Undisputed Ruler,
High King, High God.
- 1 Tim. 6:14b-15 (The Message)

**Comment by hlamer** [comment]
`Main menu` -> `System` -> `Preferences` -> `Apperance`.
On this screen I have `Mint-X` theme and 4 buttons: Delete, Save As, **Customize**, Install

**Comment by bjones1** [comment]
Hmmm, still can't find this. Are you using Mint 16 with Cinnamon? Or is
this some other version / window manager?

On Thu, Jun 25, 2015 at 3:30 AM, Andrei Kopats <notifications@github.com>
wrote:

> Main menu -> System -> Preferences -> Apperance.
> On this screen I have Mint-X theme and 4 buttons: Delete, Save As, *
> Customize*, Install
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hlamer/enki/pull/284#issuecomment-115161617>.
>



-- 
Bryan A. Jones, Ph.D.
Associate Professor
Department of Electrical and Computer Engineering
231 Simrall / PO Box 9571
Mississippi State University
Mississippi state, MS 39762
http://www.ece.msstate.edu/~bjones
bjones AT ece DOT msstate DOT edu
voice 662-325-3149
fax 662-325-2298

Our Master, Jesus Christ, is on his way. He'll show up right on
time, his arrival guaranteed by the Blessed and Undisputed Ruler,
High King, High God.
- 1 Tim. 6:14b-15 (The Message)

**Comment by hlamer** [comment]
Mint 16 + Mate

**Pull request merged**
